### ISSUE TITLE
inaccurate/misleading naming

### ISSUE THREAD

**Issue by Theblackcat98** [DRIgnazGortngschirl/bambulab-studio-orca-slicer-presets#4]
Hi, I wanted to give a heads up since I noticed you mentioned you use a naming scheme for your files; but under the readme in ~/main/process you label 'NOZLESIZE' as what it's actually layer height.

https://github.com/DRIgnazGortngschirl/bambulab-studio-orca-slicer-presets/tree/main/process

Hope this helps and save someone a headache :)

**Comment by DRIgnazGortngschirl** [comment]
Hi @Theblackcat98

Thanks for the heads-up, it's corrected now!
